### ISSUE TITLE
Error with chart: Cannot read property 'reference' of undefined

### ISSUE THREAD

**Issue by jblok** [ForestAdmin/forest-express-mongoose#107]
## Expected behavior

I created a Repartition chart that for one of my models. The "Group By" is set to a field that, in my model is a ref to another model. The UI sends this in the body of the request 

```
{
  aggregate:"Count"
  collection:"Recording"
  filters:[]
  group_by_field:"organisation:name"
  query:null
  time_range:null
  timezone:"+01:00"
  type:"Pie"
}
```

## Actual behavior

I get an error response back from the API "Cannot read property 'reference' of undefined" with this stack

If I curl the request the UI makes, but change the body so that the field `group_by_field` equals `organisation` rather than `organisation:name`, it works! So not sure if the UI should change or the API.

## Failure Logs

TODO: Please include any relevant log snippets, if necessary.

```
TypeError: Cannot read property 'reference' of undefined
    at getReference (/node_modules/forest-express-mongoose/services/pie-stat-getter.js:17:18)
    at PieStatGetter.perform (/node_modules/forest-express-mongoose/services/pie-stat-getter.js:35:32)
    at get (/node_modules/forest-express/dist/routes/stats.js:20:79)
    at Layer.handle [as handle_request] (/node_modules/forest-express/node_modules/express/lib/router/layer.js:95:5)
...
```

TODO: Please provide any relevant information about your setup.

* Package Version:2.9.0
* Express Version: 4.15.2
* Mongoose Version: 5.1.2
* MongoDB Version: 3.6

**Comment by jblok** [comment]
Hi, any update on tis bug?

**Comment by ItsMrAkhil** [comment]
I'm also facing the same issue. Maybe it's not related to versions of packages.
