### ISSUE TITLE
ForestAdmin can't handle a single condition

### ISSUE THREAD

**Issue by roopakv** [ForestAdmin/forest-express-mongoose#127]
## Expected behavior

I should be able to add a single filter

## Actual behavior

If i add a single filter it fails

## Failure Logs

```
0|admin-server  | [forest] 🌳🌳🌳  Unexpected error: $and/$or/$nor must be a nonempty array
0|admin-server  | MongoError: $and/$or/$nor must be a nonempty array
0|admin-server  |     at queryCallback (/Users/roopak/workspace/spoke/node_modules/mongodb-core/lib/cursor.js:248:25)
0|admin-server  |     at /Users/roopak/workspace/spoke/node_modules/mongodb-core/lib/connection/pool.js:532:18
0|admin-server  |     at args.(anonymous function) (/Users/roopak/workspace/spoke/node_modules/event-loop-inspector/index.js:138:29)
0|admin-server  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|admin-server  |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)
0|admin-server  | (node:65144) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

## Context

* Package Version: 2.14.2
* Express Version: 4.15.4
* Mongoose Version: 5.2.13
* MongoDB Version: 3.6

**Comment by arnaudbesnier** [comment]
Hi @roopakv,

Can you detail exactly what you're trying to do?
Is it about charts? Is it about records display? Is it about anything else?

Thanks

**Comment by louisteenbrink** [comment]
@roopakv do you confirm this is fixed now?

**Comment by arnaudbesnier** [comment]
No news about the issue, I close this issue.
